# Generated by Django 5.1.4 on 2024-12-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('suitable_for', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
